// Daftar bahasa yang didukung google-translate-api-x
// Sumber: node_modules/google-translate-api-x/lib/languages.cjs

export interface Language {
  code: string;
  name: string;
}

// Bahasa populer ditampilkan paling atas
export const POPULAR_LANGUAGES: Language[] = [
  { code: "auto", name: "Deteksi Otomatis" },
  { code: "id",   name: "Indonesia" },
  { code: "en",   name: "English" },
  { code: "ja",   name: "Japanese" },
  { code: "ko",   name: "Korean" },
  { code: "zh-CN", name: "Chinese (Simplified)" },
  { code: "zh-TW", name: "Chinese (Traditional)" },
  { code: "ar",   name: "Arabic" },
  { code: "fr",   name: "French" },
  { code: "de",   name: "German" },
  { code: "es",   name: "Spanish" },
  { code: "pt",   name: "Portuguese" },
  { code: "ru",   name: "Russian" },
  { code: "hi",   name: "Hindi" },
  { code: "th",   name: "Thai" },
  { code: "vi",   name: "Vietnamese" },
  { code: "ms",   name: "Malay" },
  { code: "tl",   name: "Filipino" },
  { code: "tr",   name: "Turkish" },
  { code: "it",   name: "Italian" },
  { code: "nl",   name: "Dutch" },
  { code: "pl",   name: "Polish" },
  { code: "sv",   name: "Swedish" },
  { code: "uk",   name: "Ukrainian" },
];

export const ALL_LANGUAGES: Language[] = [
  ...POPULAR_LANGUAGES,
  { code: "ab",       name: "Abkhaz" },
  { code: "ace",      name: "Acehnese" },
  { code: "ach",      name: "Acholi" },
  { code: "af",       name: "Afrikaans" },
  { code: "sq",       name: "Albanian" },
  { code: "am",       name: "Amharic" },
  { code: "hy",       name: "Armenian" },
  { code: "as",       name: "Assamese" },
  { code: "ay",       name: "Aymara" },
  { code: "az",       name: "Azerbaijani" },
  { code: "ban",      name: "Balinese" },
  { code: "bm",       name: "Bambara" },
  { code: "eu",       name: "Basque" },
  { code: "be",       name: "Belarusian" },
  { code: "bn",       name: "Bengali" },
  { code: "bho",      name: "Bhojpuri" },
  { code: "bs",       name: "Bosnian" },
  { code: "bg",       name: "Bulgarian" },
  { code: "yue",      name: "Cantonese" },
  { code: "ca",       name: "Catalan" },
  { code: "ceb",      name: "Cebuano" },
  { code: "ny",       name: "Chichewa" },
  { code: "co",       name: "Corsican" },
  { code: "hr",       name: "Croatian" },
  { code: "cs",       name: "Czech" },
  { code: "da",       name: "Danish" },
  { code: "dv",       name: "Dhivehi" },
  { code: "doi",      name: "Dogri" },
  { code: "dz",       name: "Dzongkha" },
  { code: "eo",       name: "Esperanto" },
  { code: "et",       name: "Estonian" },
  { code: "ee",       name: "Ewe" },
  { code: "fo",       name: "Faroese" },
  { code: "fj",       name: "Fijian" },
  { code: "fi",       name: "Finnish" },
  { code: "fy",       name: "Frisian" },
  { code: "gl",       name: "Galician" },
  { code: "ka",       name: "Georgian" },
  { code: "el",       name: "Greek" },
  { code: "gn",       name: "Guarani" },
  { code: "gu",       name: "Gujarati" },
  { code: "ht",       name: "Haitian Creole" },
  { code: "ha",       name: "Hausa" },
  { code: "haw",      name: "Hawaiian" },
  { code: "he",       name: "Hebrew" },
  { code: "hmn",      name: "Hmong" },
  { code: "hu",       name: "Hungarian" },
  { code: "is",       name: "Icelandic" },
  { code: "ig",       name: "Igbo" },
  { code: "ilo",      name: "Ilocano" },
  { code: "ga",       name: "Irish" },
  { code: "jw",       name: "Javanese" },
  { code: "kn",       name: "Kannada" },
  { code: "kk",       name: "Kazakh" },
  { code: "km",       name: "Khmer" },
  { code: "rw",       name: "Kinyarwanda" },
  { code: "ko",       name: "Korean" },
  { code: "ku",       name: "Kurdish (Kurmanji)" },
  { code: "ckb",      name: "Kurdish (Sorani)" },
  { code: "ky",       name: "Kyrgyz" },
  { code: "lo",       name: "Lao" },
  { code: "la",       name: "Latin" },
  { code: "lv",       name: "Latvian" },
  { code: "ln",       name: "Lingala" },
  { code: "lt",       name: "Lithuanian" },
  { code: "lg",       name: "Luganda" },
  { code: "lb",       name: "Luxembourgish" },
  { code: "mk",       name: "Macedonian" },
  { code: "mg",       name: "Malagasy" },
  { code: "ml",       name: "Malayalam" },
  { code: "mt",       name: "Maltese" },
  { code: "mi",       name: "Maori" },
  { code: "mr",       name: "Marathi" },
  { code: "mn",       name: "Mongolian" },
  { code: "my",       name: "Myanmar (Burmese)" },
  { code: "ne",       name: "Nepali" },
  { code: "no",       name: "Norwegian" },
  { code: "or",       name: "Odia (Oriya)" },
  { code: "om",       name: "Oromo" },
  { code: "ps",       name: "Pashto" },
  { code: "fa",       name: "Persian" },
  { code: "pa",       name: "Punjabi" },
  { code: "qu",       name: "Quechua" },
  { code: "ro",       name: "Romanian" },
  { code: "sm",       name: "Samoan" },
  { code: "sa",       name: "Sanskrit" },
  { code: "gd",       name: "Scots Gaelic" },
  { code: "sr",       name: "Serbian" },
  { code: "st",       name: "Sesotho" },
  { code: "sn",       name: "Shona" },
  { code: "sd",       name: "Sindhi" },
  { code: "si",       name: "Sinhala" },
  { code: "sk",       name: "Slovak" },
  { code: "sl",       name: "Slovenian" },
  { code: "so",       name: "Somali" },
  { code: "su",       name: "Sundanese" },
  { code: "sw",       name: "Swahili" },
  { code: "tg",       name: "Tajik" },
  { code: "ta",       name: "Tamil" },
  { code: "tt",       name: "Tatar" },
  { code: "te",       name: "Telugu" },
  { code: "bo",       name: "Tibetan" },
  { code: "ti",       name: "Tigrinya" },
  { code: "to",       name: "Tongan" },
  { code: "tk",       name: "Turkmen" },
  { code: "ak",       name: "Twi" },
  { code: "ur",       name: "Urdu" },
  { code: "ug",       name: "Uyghur" },
  { code: "uz",       name: "Uzbek" },
  { code: "cy",       name: "Welsh" },
  { code: "xh",       name: "Xhosa" },
  { code: "yi",       name: "Yiddish" },
  { code: "yo",       name: "Yoruba" },
  { code: "zu",       name: "Zulu" },
];

// Deduplicate berdasarkan code (POPULAR sudah masuk, hindari duplikat)
const popularCodes = new Set(POPULAR_LANGUAGES.map(l => l.code));
export const LANGUAGES: Language[] = [
  ...POPULAR_LANGUAGES,
  ...ALL_LANGUAGES.filter(l => !popularCodes.has(l.code)),
];

// Bahasa yang TIDAK bisa jadi target (hanya source)
export const SOURCE_ONLY_CODES = new Set(["auto"]);

export const DEFAULT_FROM = "id";
export const DEFAULT_TO   = "ja";
